log:
  level: debug
  disable_sentry: true

db:
  url: postgres://book:book@localhost:2543/book?sslmode=disable

mime_types:
  banner:
    - image/png
    - image/jpeg
    - image/jpg

promocodes:
  name: promocode_checker
  decimal: 2 # number of digits after decimal point
  runner:
    normal_period: 10 # in seconds
    min_abnormal_period: 1 # in seconds
    max_abnormal_period: 3000  # in seconds

task_cleaner:
  name: task_cleaner # Name to be displayed in logs
  runner: # Period settings
    normal_period: 10s
    min_abnormal_period: 10s
    max_abnormal_period: 10s
  cleaning_period: 20m # minutes / How long task can stay unresolved until it will be deleted

ipfser:
  base_uri: https://gateway.pinata.cloud/ipfs/
  number_of_retries: 5
  retry_period: 2s

api: # Api restrictions
  max_failed_attempts: 10
  request_delay: 5m

mint: # Parameters for mint signature generation
  signer: b5b6c7a28756d349ac1e7f7bf11fa885ea7d761c498c6f9803ad6b03675ad4a9
  precision: 18
  expiration: 5m
  chain_id: 137

transaction:
  private_key: private_key
  gas_limit: 300000
  max_gas_price: 400 # in GWEI

connector: # Connector to other APIs
  url:
  token:

listener:
  addr: :8765

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: core-svc
  service_port: 80
